### ISSUE TITLE
Please publish this plugin to npm

### ISSUE THREAD

**Issue by wingsof** [zdy1988/vue-treeselect#1]
Hello,

I love your plugin and eager to use this but couldn't find your plugin on npm registry.
Would you please publish your plugin to npm so that I can use your plugin with npm install command?

**Comment by zdy1988** [comment]
:point_right:  **npm install vue-treeselect**

This Plugin is based on vue-jstree, Some "props" can be used for reference !

Thank you for your love! :smile:
