### ISSUE TITLE
怎么改每个树前面的icon

### ISSUE THREAD

**Issue by KsssAlleria** [zdy1988/vue-treeselect#4]

**Comment by zdy1988** [comment]
你看到测试数据中某项包含icon属性，这个属性是树中节点的css class，如果你使用的是font awesome字体图标，直接用 icon：“fa fa-warning”  或者 其他自定义css都行， 你也可以家一些状态颜色的 css ，比如  icon：“fa fa-warning icon-state-danger”  当然 “icon-state-danger” 需要你自己实现
