### ISSUE TITLE
请问一下  单选的情况下怎样初始化

### ISSUE THREAD

**Issue by TTGitHub2017** [zdy1988/vue-treeselect#5]
![image](https://user-images.githubusercontent.com/28435604/34146582-9a46c484-e4d5-11e7-8154-e46a484c1d64.png)

**Comment by zdy1988** [comment]
默认情况下就是单选，加上 multiple 才会是多选

**Comment by TTGitHub2017** [comment]
我的意思是  初始化的时候  默认选中第一个值或者其他值  下面的列表可以通过selected属性控制  但是上面的文本框中的值怎样让它显示对应的值

**Comment by zdy1988** [comment]
嗯，我发现我理解错了，貌似我忘了做绑定，稍等... - - !

**Comment by TTGitHub2017** [comment]
恩恩  好了说一下  谢谢

**Comment by zdy1988** [comment]
我发布了新版本，根据你的指定的 **value-field-name** 的字段去匹配选取，默认是 value 字段，例子里制定的是 id ，这个你可以自己指定

**Comment by TTGitHub2017** [comment]
好的  谢谢

**Comment by zdy1988** [comment]
值不要重复的，重复的 单选情况下 只会选择第一个 ，多选形况下 会选择所有能匹配到的！

**Comment by TTGitHub2017** [comment]
恩恩  好的  是根据value-field-name这个属性定义的值来决定的吧

**Comment by zdy1988** [comment]
嗯，是

**Comment by TTGitHub2017** [comment]
ok  我现在更新一下   谢谢楼主的分享

**Comment by zdy1988** [comment]
多谢支持，哈哈
